version: '3.8'
services:
  backend:
    image: blabla:version #blabla:version TODO
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - service-db
    environment:
      - SERVER_PORT= 8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://service-db/  #dbname#
      - SPRING_PROFILES_ACTIVE=prod

  service-db:
    image: postgres:14.7-alpine
    environment:
      POSTGRES_USER: #username from yml
      POSTGRES_PASSWORD: #password from yml
      POSTGRES_DB: #dbname
      POSTGRES_INITDB_LOCALE: en_US.utf8
    ports:
      - "15432:5432"
    volumes:
      - ./infrastructure/db/1_create_db.sql:/docker-entrypoint-initdb.d/1_create_db.sql
      - db-data:/var/lib/postgresql/data
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin4_container
    image: dpage/pgadmin4:7
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  db-data:
  pgadmin-data: