spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=${ACCOUNT_SERVICE_PATH:/api/v2/accounts/**}
          filters:
            - AuthenticationFilter

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=${CUSTOMER_SERVICE_PATH:/api/v1/customers/**}
          filters:
            - AuthenticationFilter

        - id: currency-service
          uri: lb://CURRENCY-SERVICE
          predicates:
            - Path=${CURRENCY_SERVICE_PATH:/api/v1/currencies/**}
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=${AUTH_SERVICE_PATH:/api/v1/auth/**}

        - id: cloud-config-service
          uri: lb://CLOUD-CONFIG-SERVICE
          predicates:
            - Path=/cloud-configs/**

        - id: account-card-service
          uri: lb://ACCOUNT-CARD-SERVICE
          predicates:
            - Path=/api/v1/accounts/**
          filters:
            - AuthenticationFilter

        - id: account-card-service
          uri: lb://ACCOUNT-CARD-SERVICE
          predicates:
            - Path=/api/v1/cards/**

        - id: credit-service
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/api/v1/credits/**
          filters:
            - AuthenticationFilter



  application:
    name: BANKING-GATEWAY
eureka:
  client:
    service-url:
      defaultZone : http://${DEV_EUREKA_HOST:localhost}:${EUREKA_PORT:8761}/eureka/

token:
  secret-key: ${JWT_SECRET:jk6a9Lnyy7wWJZubVG9Cf8QtQnL3U/ArPMVcHchXiOaFaPPygc99sM2LC25kscbu}