spring:
  cloud:
    gateway:
      routes:
        - id: account-service
          uri: lb://ACCOUNT-SERVICE
          predicates:
            - Path=${ACCOUNT_SERVICE_PATH}
          filters:
            - AuthenticationFilter

        - id: customer-service
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=${CUSTOMER_SERVICE_PATH}
          filters:
            - AuthenticationFilter

        - id: currency-service
          uri: lb://CURRENCY-SERVICE
          predicates:
            - Path=${CURRENCY_SERVICE_PATH}
          filters:
            - AuthenticationFilter

        - id: auth-service
          uri: lb://AUTH-SERVICE
          predicates:
            - Path=${AUTH_SERVICE_PATH}

        - id: cloud-config-service
          uri: lb://CLOUD-CONFIG-SERVICE
          predicates:
            - Path=/cloud-configs/**

        - id: account-card-service
          uri: lb://ACCOUNT-CARD-SERVICE
          predicates:
            - Path=/api/v1/accounts/**

        - id: account-card-service
          uri: lb://ACCOUNT-CARD-SERVICE
          predicates:
            - Path=/api/v1/cards/**

        - id: credit-service
          uri: lb://CREDIT-SERVICE
          predicates:
            - Path=/api/v1/credits/**



  application:
    name: BANKING-GATEWAY

token:
  secret-key: ${JWT_SECRET}