server:
  port: 0
spring:
  application:
    name: cloud-config-service
  cloud:
    config:
      server:
        prefix: /cloud-configs # перфикс, по которому делать запрос
        git:
          Force-Pull : true
          uri: https://github.com/DiabloElf/spring-boot-configs.git # урл гит репозитория с конфигами
          default-label: master #ветка в которой будет идти поиск конфигов
          skip-ssl-validation: true
          search-paths: "configs/{application}" #configs - каталог, где лежат общие для всех конфиги
                            #application - имя подкаталога(является именем приложения), в котором будут искаться конфиги.
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/