spring:
  liquibase:
    change-log: #поставить classpath:db.changelog/db.changelog-master.xml TODO
  datasource:
    url: #url TODO
    username: #username
    password: #password
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 2000000
      connection-timeout: 30000
logging:
  config: #мб уйдет в стартер