server:
  port: 0
spring:
  application:
    name: account-card-service
  profiles:
    active: dev
  datasource:
    url: jdbc:postgresql://localhost:5555/account-card-service
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 0
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  rabbitmq:
    addresses: amqp://admin:admin@localhost:5672
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true
