server:
  port: ${PORT:0}
spring:
  application:
    name: CREDIT-SERVICE
  profiles:
    active: dev
  datasource:
    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
    show-sql: true
clevertec:
  rabbit:
    consumer:
      queue:
        credit-queue: ${RABBIT_QUEUE_NAME:credit-details}
logging:
  level:
    org:
      hibernate:
        type: trace
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    enabled: true