spring:
  datasource:
    url: jdbc:postgresql://localhost:${PROD_DB_PORT}/${DB_NAME}?currentSchema=${DEFAULT_SCHEMA}
    username: ${PROD_DB_USERNAME}
    password: ${PROD_DB_PASSWORD}
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        default_schema: ${DEFAULT_SCHEMA}
  liquibase:
    default-schema: ${DEFAULT_SCHEMA}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: ${DEFAULT_SCHEMA}
  rabbitmq:
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
    port: ${PROD_RABBIT_PORT}
    host: ${PROD_RABBIT_HOST}
    username: ${RABBIT_USERNAME}
    password: ${RABBIT_PASSWORD}
clevertec:
  rabbit:
    consumer:
      queue:
        credit-queue: ${PROD_RABBITMQ_QUEUE_NAME}
eureka:
  client:
    service-url:
      defaultZone: http://${PROD_EUREKA_HOST}:${PROD_EUREKA_PORT}/eureka/
    enabled: true