spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:${DEV_DB_PORT:5555}/${DB_NAME:account-card-service}?currentSchema=${DEFAULT_SCHEMA:credit}
    username: ${DEV_DB_USERNAME:admin}
    password: ${DEV_DB_PASSWORD:admin}
  liquibase:
    enabled: true
    default-schema: ${DEFAULT_SCHEMA:credit}
    change-log: classpath:db/changelog/db.changelog-master.yaml
    liquibase-schema: ${DEFAULT_SCHEMA:credit}
  rabbitmq:
    addresses: amqp://admin:admin@localhost:5673
    listener:
      simple:
        acknowledge-mode: auto
        prefetch: 1
  jpa:
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        default_schema: ${DEFAULT_SCHEMA:credit}
    show-sql: true
